volumes:
  #couchdb-config:
  couchdb-data:

services:
  couchdb:
    image: couchdb
    restart: unless-stopped
    ports:
      - 5984:5984
    volumes:
      - couchdb-data:/opt/couchdb/data
      #- couchdb-config:/opt/couchdb/etc/local.d
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password